#!/usr/bin/env python
# ~*~ coding=utf-8 ~*~

text = (
    '<p>'
    'Liebe Kolleginnen und Kollegen,<br>'
    '<br>'
    'der Herbst rückt langsam näher und mit ihm zahlreiche neue Bücher, '
    'die uns begeistert haben.<br>'
    'Unsere Empfehlungsliste im <b>Frühjahr 2020</b> haben Sie bekommen '
    'und wir bedanken uns ganz herzlich für die Belegexemplare, die Sie '
    'uns gesendet haben. Nun ist unsere <b>Empfehlungsliste</b> für den '
    '<b>Herbst</b> erschienen, die wir Ihnen im Anhang beifügen.'
    '</p>'
    '<p>'
    'Die bisher gute Zusammenarbeit mit Ihrem Verlag und Ihre positiven '
    'Rückmeldungen der letzten Jahre sind die Grundlage dafür, dass wir '
    'auch weiterhin die Leselust wecken und fördern können: bei kleinen '
    'wie großen Kunden.'
    '</p>'
    '<p>'
    'Wie jedes Jahr würden wir unsere persönliche Auswahl von Neuerscheinungen '
    'gerne bei einem gemütlichen Abend unseren Kunden vorstellen. '
    'Wahrscheinlich wird dies auf Grund der aktuellen Corona-Pandemie in '
    'dieser Form leider nicht möglich sein. Wir sind aber bereits auf der '
    'Suche nach einem alternativen Format, um die Neuerscheinungen, die '
    'uns besonders am Herzen liegen, unseren Kunden auf persönlicherem Weg '
    'präsentieren zu können.'
    '</p>'
    '<p>'
    'Wie gewohnt wird der Katalog aber an <b>etwa 650 öffentliche und '
    'kirchliche Bibliotheken</b> gesandt. Zudem schreiben wir alle '
    '<b>Schulbibliotheken</b> des Postleitzahlengebietes 79xxx an. '
    'Wir beraten und bestücken außerdem <br>Kindergärten und Schulen</b> mit Novitäten.'
    '</p>'
    '<p>'
    'Darüber hinaus gestalten wir auch 2021 Projekte und Veranstaltungen '
    'in Zusammenarbeit mit regionalen Partnern, wie dem <b>Kulturamt</b>, '
    'dem <b>Museum für Neue Kunst</b> und dem '
    '<b><a href="https://www.fuechsleclub.de/lesetipps">Füchsle Club des '
    'SC Freiburg</a></b>, um nur einige zu nennen.'
    '</p>'
    '<p>'
    'Die neuen Entdeckungen ergänzen unser Sortiment und sind unentbehrlich '
    'für die individuelle Beratung. Sie finden unsere Empfehlungslisten auch '
    'regelmäßig auf unserer <b><a href="https://fundevogel.de">Webseite</a></b> nebst '
    'persönlichen Buchtipps.'
    '</p>'
    '<p>'
    'Wir würden uns sehr freuen, wenn Sie unsere Arbeit weiterhin mit je '
    '<b>einem oder zwei Belegexemplaren</b> des jeweiligen Titels '
    'unterstützen und damit honorieren.'
    '</p>'
    '<p>'
    'Die entsprechenden Titel aus Ihrem Verlag finden Sie wie folgt:'
    '</p>'
)

signature = (
    '<p>'
    'Mit besten Grüßen aus dem Fundevogel<br>'
    '<br>'
    'Claus-Peter Jepsen und Team'
    '</p>'
    '--'
    '<br>'
    'Lieber barfuß als ohne Buch!'
    '<p>'
    'Kinder- und Jugendbuchhandlung Fundevogel<br>'
    'Inh.: Claus-Peter Jepsen<br>'
    'Marienstr. 13<br>'
    '79098 Freiburg<br>'
    '</p>'
    '<p>'
    'Telefon: 0761/25218<br>'
    'Fax: 0761/30041<br>'
    'E-Mail: info@fundevogel.de<br>'
    'Internet: www.fundevogel.de<br>'
    '</p>'
    '<p>'
    'VK.-Nr.: 31776<br>'
    'Volksbank Freiburg: Konto 724 070 8 /BLZ 680 900 00<br>'
    'Bankverbindung Ausland: '
    'IBAN DE 266 809 0000000 7240708 / '
    'BIC GENO DE 61 FR 1<br>'
    'Ust. Id. DE 142035994<br>'
    '</p>'
)
